#!/usr/bin/env bash
# this script installs nginx and configures it on a remote server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
